// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	companyin "github.com/touchtechnologies-product/go-blueprint-clean-architecture-for-kafka/service/company/companyin"

	domain "github.com/touchtechnologies-product/go-blueprint-clean-architecture-for-kafka/domain"

	mock "github.com/stretchr/testify/mock"

	out "github.com/touchtechnologies-product/go-blueprint-clean-architecture-for-kafka/service/company/out"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, input
func (_m *Service) Create(ctx context.Context, input *companyin.CreateInput) (string, error) {
	ret := _m.Called(ctx, input)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *companyin.CreateInput) string); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *companyin.CreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, input
func (_m *Service) Delete(ctx context.Context, input *companyin.DeleteInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *companyin.DeleteInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, input
func (_m *Service) List(ctx context.Context, input *domain.PageOption) (int, []*out.CompanyView, error) {
	ret := _m.Called(ctx, input)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PageOption) int); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 []*out.CompanyView
	if rf, ok := ret.Get(1).(func(context.Context, *domain.PageOption) []*out.CompanyView); ok {
		r1 = rf(ctx, input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*out.CompanyView)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *domain.PageOption) error); ok {
		r2 = rf(ctx, input)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Read provides a mock function with given fields: ctx, input
func (_m *Service) Read(ctx context.Context, input *companyin.ReadInput) (*out.CompanyView, error) {
	ret := _m.Called(ctx, input)

	var r0 *out.CompanyView
	if rf, ok := ret.Get(0).(func(context.Context, *companyin.ReadInput) *out.CompanyView); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*out.CompanyView)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *companyin.ReadInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, input
func (_m *Service) Update(ctx context.Context, input *companyin.UpdateInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *companyin.UpdateInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
